const TROOPS_PER_TERRITORY = 4;
const SIMULATION_TICK_MS = 50;
const ECONOMY_TICKS_PER_SECOND = 10;
const ECONOMY_CYCLE_SECONDS = 10;
const NAME_DISPLAY_TERRITORY = 50;
const BOT_COUNT = 200;

module.exports = {
  TROOPS_PER_TERRITORY,
  SIMULATION_TICK_MS,
  ECONOMY_TICKS_PER_SECOND,
  ECONOMY_CYCLE_SECONDS,
  NAME_DISPLAY_TERRITORY,
  BOT_COUNT
};
